FROM node:16
WORKDIR C:\Users\Stratos\Desktop\01ECE\0__Thesis\Code\CVS-Test
# RUN npm install -g ganache-cli
# RUN npm install -g truffle
CMD ["bash", "-c", "ganache-cli -h ganache & sleep 5 && truffle migrate && tail -f /dev/null"]
